package com.steve1316.uma_android_automation.bot.solver

import com.steve1316.uma_android_automation.types.RaceGrade
import com.steve1316.uma_android_automation.types.TrackDistance
import com.steve1316.uma_android_automation.types.TrackSurface

/**
 * Filter predicate used by [EpithetMatcher.WinCount] to decide whether a race counts toward
 * the matcher's tally. Mirrors the structured shape produced by the gametora epithet scraper.
 *
 * All non-null / non-empty fields combine with logical AND. Empty / null fields are ignored.
 */
data class EpithetFilter(
    val terrain: TrackSurface? = null,
    val grade: RaceGrade? = null,
    val gradeAtLeastOpen: Boolean = false,
    val gradedOnly: Boolean = false,
    val distanceTypes: Set<TrackDistance> = emptySet(),
    val raceTracks: Set<String> = emptySet(),
    val nameContains: String? = null,
    val nameContainsCountry: Boolean = false,
)

/**
 * Structured race-condition predicate the solver evaluates against the win history.
 *
 * The flat list of matchers on an [Epithet] is interpreted as a logical AND: an epithet
 * is completed when every matcher is satisfied. `atClass` is the in-game class year prefix
 * — "Junior", "Classic", or "Senior" — for matchers that gate by class (e.g. "Japan Cup (Classic)").
 */
sealed class EpithetMatcher {
    data class WinRace(val name: String, val atClass: String? = null) : EpithetMatcher()

    data class WinRaceTimes(val name: String, val times: Int) : EpithetMatcher()

    data class WinAnyOf(
        val names: List<String>,
        val count: Int = 1,
        val atClass: String? = null,
    ) : EpithetMatcher()

    data class WinAtLeast(val names: List<String>, val count: Int) : EpithetMatcher()

    data class WinCount(val count: Int, val filter: EpithetFilter) : EpithetMatcher()

    data class EpithetAnyOf(val names: List<String>) : EpithetMatcher()

    data class EpithetAll(val names: List<String>) : EpithetMatcher()
}

/**
 * An in-game epithet (nickname) the player can complete for a stat or skill-hint reward.
 *
 * Sourced from `src/data/epithets.json`, which is generated by the EpithetScraper in
 * `src/data/main.py`. The scraper owns the human-facing fields ([name] through [notes]);
 * [dependsOn] and [matchers] are hand-curated locally so re-scrapes never clobber them.
 *
 * @property rewardKind One of "stat", "hint", or "unknown".
 * @property amount Total reward magnitude (per-stat × stat-count, or hint level).
 * @property displayAmount Per-stat amount for stat rewards; same as [amount] for hints.
 * @property dependsOn Names of prerequisite epithets that must complete first.
 * @property matchers AND-combined predicates evaluated against the win history.
 */
data class Epithet(
    val name: String,
    val category: String,
    val rewardText: String,
    val rewardKind: String,
    val amount: Int,
    val displayAmount: Int,
    val conditionText: String,
    val dependsOn: List<String>,
    val matchers: List<EpithetMatcher>,
)
